# Site settings
title: Ratul Minhaz
description: 'I am a web developer based in Dhaka, Bangladesh. I use Python for data wrangling. I want to be an omniglot.'
url: 'http://ratul.xyz/'
# url: 'http://127.0.0.1:4000'
# baseurl: '/jekyll-uno/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# static_files: images


author:
  name: 'Ratul Minhaz'
  email: me@ratul.xyz
  twitter_username: ratulotron
  facebook_username: ratulotron
  github_username:  ratulotron
  linkedin_username:  minhazratul

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  # syntax_highlighter: rouge


gems: [jekyll-paginate, jekyll-admin]
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
